version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /home/hotbpf/hot_bpf_analyzer
    stdin_open: true
    tty: true